### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Mister-Muffin** [Mr-Pine/BaumBot#1]
I am an issue :)

**Comment by Mister-Muffin** [comment]
Additionally, i am issue number 1! :relaxed:

**Comment by Mr-Pine** [comment]
Oh wow! Hallo Issue #1 :)

**Comment by Mister-Muffin** [comment]
Hello there, comment! How are you?

**Comment by Mr-Pine** [comment]
Me very good, and you, issue?

**Comment by Mister-Muffin** [comment]
I am good, but i have to leave now :)

**Comment by Mr-Pine** [comment]
:(
